from pathlib import Path
from typing import Protocol

from PIL import Image


class DisplayDriver(Protocol):
    def connect(self) -> bool: ...

    def disconnect(self) -> None: ...

    def set_brightness(self, level: int) -> None: ...

    def send_image(self, img: Image.Image, x: int, y: int) -> None: ...

    def upload_file(self, local_path: Path, remote_path: str) -> bool: ...

    def play_media(self, remote_path: str) -> None: ...

    def stop_media(self) -> None: ...
